// frontend/src/components/ImageUpload.jsx
import React, { useState } from 'react';

function ImageUpload({ onImageUpload }) {
    const [selectedImage, setSelectedImage] = useState(null);

    const handleImageChange = (e) => {
        const file = e.target.files[0];
        // setSelectedImage(URL.createObjectURL(file));
        onImageUpload(file);
    };

    return (
        <div className="my-8 p-4 border-dashed border-2 border-gray-300 rounded-lg text-center">
            <input type="file" accept="image/*" onChange={handleImageChange} className="hidden" id="upload-input"/>
            <label htmlFor="upload-input" className="cursor-pointer text-blue-600">Click to Upload Image</label>
            {/*{selectedImage && <img src={selectedImage} alt="Preview" className="mx-auto mt-4 w-1/2"/>}*/}
        </div>
    );
}

export default ImageUpload;

// frontend/src/components/ImageUpload.vue
<template>
  <div class="image-upload">
    <input
        type="file"
        accept="image/*"
        @change="onImageChange"
        id="file-upload"
        class="file-input"
    />
    <label for="file-upload" class="upload-label">上传本地图片</label>
  </div>
</template>

<script>
export default {
  name: 'ImageUpload',
  methods: {
    onImageChange(event) {
      const file = event.target.files[0];
      if (file) {
        this.$emit('image-upload', file); // 将文件对象传递给父组件
      }
    },
  },
};
</script>

<style scoped>
.image-upload {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  border: 2px dashed #ccc;
  border-radius: 8px;
  cursor: pointer;
}
.file-input {
  display: none;
}
.upload-label {
  color: #007bff;
  cursor: pointer;
}
</style>
